name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '8.1'

          - operating-system: 'ubuntu-latest'
            php-version: '8.2'

          - operating-system: 'windows-latest'
            php-version: '8.2'
            job-description: 'on Windows'

          - operating-system: 'macos-latest'
            php-version: '8.2'
            job-description: 'on macOS'

    name: PHP ${{ matrix.php-version }} ${{ matrix.job-description }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          retry_wait_seconds: 30
          command: |
            composer update --optimize-autoloader --no-interaction --no-progress ${{ matrix.composer-flags }}
            composer info -D

      - name: Run tests
        run: vendor/bin/phpunit ${{ matrix.phpunit-flags }}

      - name: Run static analysis
        run: vendor/bin/psalm.phar

      - name: Run style fixer
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: vendor/bin/php-cs-fixer --diff --dry-run -v fix
        if: runner.os != 'Windows'

      - name: Install composer-require-checker
        run: php -r 'file_put_contents("composer-require-checker.phar", file_get_contents("https://github.com/maglnet/ComposerRequireChecker/releases/download/3.7.0/composer-require-checker.phar"));'
        if: runner.os != 'Windows' && matrix.composer-require-checker-version != 'none'

      - name: Run composer-require-checker
        run: php composer-require-checker.phar check composer.json --config-file $PWD/composer-require-check.json
        if: runner.os != 'Windows' && matrix.composer-require-checker-version != 'none'

      - name: Autobahn
        if: runner.os == 'Linux' && matrix.php-version == '8.2'
        shell: 'script -q -e -c "bash {0}"'
        run: |
          docker run -ti -d --rm -v ${PWD}:/app --net="host" --name amp-websocket-server php:8.2-cli php /app/test-autobahn/server.php
          docker run -ti --rm -v ${PWD}/test-autobahn/config:/config -v ${PWD}/test-autobahn/reports:/reports --net="host" --name fuzzingclient crossbario/autobahn-testsuite wstest -m fuzzingclient -s config/fuzzingclient.json
          php test-autobahn/report.php

      - name: Archive autobahn artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: autobahn-results
          retention-days: 1
          path: |
            test-autobahn/reports